version: 2
jobs:
  build:
    docker:
      - image: changefinance/flutter-builder-docker:1.4.18
    environment:
      CODECOV_TOKEN: 2946bed5-f2c8-4478-a9d8-e553cce48cbc
    steps:
      - checkout
      - run: flutter doctor -v
      - run: flutter analyze
      - run: flutter -v test --concurrency=2

  update-version:
    docker:
      - image: alpine/git:1.0.7
    steps:
      - add_ssh_keys:
          fingerprints:
            - "50:63:2f:5a:ab:82:6d:59:8d:fd:57:5a:b3:2f:c3:c1"
      - checkout
      - run: 
          name: Update version
          command: |
            echo `git describe --tags --abbrev=0 | awk -F. '{$NF+=1; OFS="."; print $0}'` >> $VERSION
            git tag $VERSION
      - run: git push --tags

workflows:
  version: 2
  flutter-ui-kit-workflow:
    jobs:
      - build
      - update-version:
          filters:
            branches:
              only: auto-tag-release
