version: 2
jobs:
  build:
    docker:
      - image: changefinance/flutter-builder-docker:1.4.18
    environment:
      CODECOV_TOKEN: 2946bed5-f2c8-4478-a9d8-e553cce48cbc
    steps:
      - checkout
      - run: flutter doctor -v
      - run: flutter analyze
      - run: flutter -v test --concurrency=2

  update-version:
    steps:
      - checkout
      - run: VERSION=`git describe --tags --abbrev=0 | awk -F. '{$NF+=1; OFS="."; print $0}'`
      - run: git tag $VERSION
      - run: git push --tags

workflows:
  version: 2
  changeapp-workflow:
    jobs:
      - build
      - update-version:
          requires:
            - build
          filters:
            branches:
              only: auto-tag-release
