name: Master

on:
  push:
    branches:
      - 'master'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
#  update-version:
#    name: Update Flutter UI Kit Version
#    runs-on: ubuntu-18.04
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          repository: ChangeFinance/flutter_ui_kit
#          token: ${{ secrets.REPO_CI_TOKEN }}
#      - run: sh ./scripts/increment-git-tag-patch.sh
