name: Master

on:
  push:
    branches:
      - 'master'

jobs:
  update-version:
    name: Update Flutter UI Kit Version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ChangeFinance/flutter_ui_kit
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false